name: demo

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test-demo:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.9"]
        framework: [tensorflow, pytorch]
    steps:
      - if: matrix.os == 'macos-latest'
        name: Install MacOS prerequisites
        run: brew install cairo pango gdk-pixbuf libffi
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - if: matrix.framework == 'tensorflow'
        name: Cache python modules (TF)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('demo/tf-requirements.txt') }}
      - if: matrix.framework == 'pytorch'
        name: Cache python modules (PT)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pkg-deps-${{ matrix.python }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('demo/pt-requirements.txt') }}

      - if: matrix.framework == 'tensorflow'
        name: Install dependencies (TF)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[tf,viz,html] --upgrade
          pip install -r demo/tf-requirements.txt
      - if: matrix.framework == 'pytorch'
        name: Install dependencies (PT)
        run: |
          python -m pip install --upgrade pip
          pip install -e .[torch,viz,html] --upgrade
          pip install -r demo/pt-requirements.txt

      - if: matrix.framework == 'tensorflow'
        name: Run demo (TF)
        env:
            USE_TF: 1
        run: |
          streamlit --version
          screen -dm streamlit run demo/app.py
          sleep 10
          curl http://localhost:8501/docs
      - if: matrix.framework == 'pytorch'
        name: Run demo (PT)
        env:
            USE_TORCH: 1
        run: |
          streamlit --version
          screen -dm streamlit run demo/app.py
          sleep 10
          curl http://localhost:8501/docs
